### ISSUE TITLE
已失效

### ISSUE THREAD

**Issue by sannire** [iamfugui/YouTubeADB#16]
插件已失效，会被油管侦测弹窗

**Comment by iamfugui** [comment]
将微信号发我的邮箱了解情况zgh0118c@gmail.com

**Comment by sannire** [comment]
微信号cngsxb




该邮件从移动设备发送




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iamfugui/YouTubeADB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月4日(星期二) 晚上9:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iamfugui/YouTubeADB] 已失效 (Issue #16)





 
***@***.***
