### ISSUE TITLE
脚本被YouTube自动删除

### ISSUE THREAD

**Issue by AeonsYu** [iamfugui/YouTubeADB#3]
脚本一开始能够生效，但在观看数个视频后被YouTube检测并自动删除

**Comment by iamfugui** [comment]
我复现不了你说的，这个删除是固定观看视频数量触发还是随机？

**Comment by Rnreck** [comment]
应该是随机的

**Comment by Rnreck** [comment]
我现在看视频第一个就会出现YouTube不允许使用广告拦截器

**Comment by iamfugui** [comment]
确定没在使用其它插件吗哥们？有其他人给我讲过这个问题，但我没碰到过。

**Comment by Rnreck** [comment]
没有其他的插件，浏览器chrome，插件用tampermonkey管理的

**Comment by ner00** [comment]
Maybe a new YouTube countermeasure for some users, Google is known to apply changes to test groups first; for me it still works fine.

**Comment by iamfugui** [comment]
> 没有其他的插件，浏览器chrome，插件用tampermonkey管理的

可能像ner00说的一样，你可以另外注册一个账号试试看，我没有其它方法。

**Comment by ShotoZhao** [comment]
是不是被检测到了？

**Comment by iamfugui** [comment]
有问题的账号，把微信号发我邮箱zgh0118c@gmail.com，我找你单独测试

**Comment by iamfugui** [comment]
其它人要解决问题的请联系我邮箱
