### ISSUE TITLE
在主页信息流界面点击三点-添加到队列-右下角小窗状态下播放，播放广告无法拦截也无法跳过

### ISSUE THREAD

**Issue by yyd003** [iamfugui/YouTubeADB#4]
![image](https://github.com/iamfugui/YouTube-AD-Blocker/assets/19585311/818ea372-022a-4758-8e02-6500a14f99d7)

**Comment by iamfugui** [comment]
先记下了，这个暂时没有好的思路解决。谢谢反馈。

**Comment by iamfugui** [comment]
解决
