### ISSUE TITLE
好像对我失效了

### ISSUE THREAD

**Issue by xnor-jetlon** [iamfugui/YouTubeADB#6]
屏蔽不掉，也跳不过，F5刷新一下倒是没有了，不过视频就重头播放了😂

**Comment by iamfugui** [comment]
被重点关注？也许你可以把你的账号给我试一下。可以的话，发我邮箱zgh0118c@gmail.com

**Comment by xnor-jetlon** [comment]
是用google账号登录的youtube，这样可以账号异地登录么？抑或还需要手机授权？



| |
建良
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月11日 18:48 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [iamfugui/YouTubeADB] 好像对我失效了 (Issue #6) |

***@***.***

**Comment by iamfugui** [comment]
不知道，先加我QQ吧520071162，看看怎么登录上去。

**Comment by iamfugui** [comment]
那你发你的微信号到我邮箱上吧

**Comment by xnor-jetlon** [comment]
大佬威武
