### ISSUE TITLE
已经被油管针对了

### ISSUE THREAD

**Issue by m3lab-zzl** [iamfugui/YouTubeADB#7]
现在油管会检测拦截插件的存在，并且要求关闭，否则三个视频后就不让看了，如图：

![image](https://github.com/iamfugui/YouTubeADB/assets/102862066/453acf5b-e134-4fd6-9c3a-20418df5d0ad)

有什么办法可以伪装看了广告从而绕开这个限制么？

**Comment by Yueby** [comment]
俺也一样

**Comment by iamfugui** [comment]
发账号给我试试zgh0118c@gmail.com

**Comment by m3lab-zzl** [comment]
奇怪的是这个屏蔽的弹窗似乎是随机的，我这两天使用又正常了

**Comment by iamfugui** [comment]
想解决问题的，把你的微信号发到我邮箱，我加你。

**Comment by iamfugui** [comment]
其它人要解决问题的请联系我邮箱
